// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMcA3l74B_nx29leBZj4-jpDIbJWGvQc',
    appId: '1:29765040223:web:4a3f04cfbad94037f003ea',
    messagingSenderId: '29765040223',
    projectId: 'remin-dere',
    authDomain: 'remin-dere.firebaseapp.com',
    databaseURL: 'https://remin-dere-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'remin-dere.appspot.com',
    measurementId: 'G-9LNVWRVT7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGCdk1rWor1uqDxZEKwcDQRSM2I5_i6g',
    appId: '1:29765040223:android:c99253eb12040654f003ea',
    messagingSenderId: '29765040223',
    projectId: 'remin-dere',
    databaseURL: 'https://remin-dere-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'remin-dere.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQajI4-NSRB2INNItKgukwIMIyLpY47Q0',
    appId: '1:29765040223:ios:fbff4f1bbb085fe2f003ea',
    messagingSenderId: '29765040223',
    projectId: 'remin-dere',
    databaseURL: 'https://remin-dere-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'remin-dere.appspot.com',
    androidClientId: '29765040223-rit6h8l0rerl3u5urauf1bbc8caovrds.apps.googleusercontent.com',
    iosClientId: '29765040223-8pvc0rsqnec58djticjdkksagog3825l.apps.googleusercontent.com',
    iosBundleId: 'com.example.remindere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQajI4-NSRB2INNItKgukwIMIyLpY47Q0',
    appId: '1:29765040223:ios:fbff4f1bbb085fe2f003ea',
    messagingSenderId: '29765040223',
    projectId: 'remin-dere',
    databaseURL: 'https://remin-dere-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'remin-dere.appspot.com',
    androidClientId: '29765040223-rit6h8l0rerl3u5urauf1bbc8caovrds.apps.googleusercontent.com',
    iosClientId: '29765040223-8pvc0rsqnec58djticjdkksagog3825l.apps.googleusercontent.com',
    iosBundleId: 'com.example.remindere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUMcA3l74B_nx29leBZj4-jpDIbJWGvQc',
    appId: '1:29765040223:web:36ee4e907f5f5ad5f003ea',
    messagingSenderId: '29765040223',
    projectId: 'remin-dere',
    authDomain: 'remin-dere.firebaseapp.com',
    databaseURL: 'https://remin-dere-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'remin-dere.appspot.com',
    measurementId: 'G-L6NEN6R3T7',
  );

}